Replace contract body encoding from hex to utf8
onflow/flow-cli pull request #1220
Opened 2023-09-26 12:36 UTC by nozim

Closes #1195 

## Description

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2023-09-26 18:48 UTC, chasefleming commented
@nozim Looks like this breaks the tests

2023-09-26 18:49 UTC, chasefleming requested changes
@nozim looks like this breaks the tests

2023-09-26 19:03 UTC, nozim commented
@chasefleming will have a look. Thanks

2023-09-27 23:59 UTC, chasefleming approved these changes

2023-09-28 00:00 UTC, merged