add crescendo support
onflow/flow-cli pull request #1351
Opened 2024-01-17 21:49 UTC by ianthpun

Closes #???

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2024-01-18 00:05 UTC, ianthpun commented on internal/transactions/build.go
> +	//|| address.IsValid(flowsdk.Crescendo) //TODO: add crescendo, it is missing in flowsdk
need this merged first https://github.com/onflow/flow-go-sdk/pull/558

2024-01-18 00:05 UTC, ianthpun commented on internal/util/util.go
> +		// flowsdk.Crescendo TODO: add crescendo
need this merged first https://github.com/onflow/flow-go-sdk/pull/558

2024-01-25 23:27 UTC, bjartek requested changes

2024-01-25 23:27 UTC, bjartek commented on internal/accounts/staking-info.go
> +	// TODO: maybe add cresecendo here?
crescendo addresses will be the same as testnet here.

2024-03-14 00:12 UTC, closed without merging

2024-03-14 00:12 UTC, ianthpun commented
closing as we aren't using crescendonet anymore