Shared Library - Tabwrite refactor
onflow/flow-cli pull request #167
Opened 2021-04-08 13:25 UTC by MaxStalker

Add `CreateTabWriter` factory method to `command` package to exclude repetition errors and DRY the code. 

Relies on  #162 to be resolved first

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

2021-04-08 15:03 UTC, sideninja commented on docs/get-status.md
> +### Network
Copy paste from template all the global flags

2021-04-08 15:05 UTC, sideninja commented on internal/status/status.go
> +		proj, err := project.Load(globalFlags.ConfigPath)
Project is already loaded in services, use the loaded project in service layer and return the values you want with multiple returns.

2021-04-08 15:07 UTC, sideninja commented on internal/status/status.go
> +func (r *Result) GetStatus() string {
This method shouldn't be exported as it doesn't comply with Result interface

2021-04-08 15:07 UTC, sideninja commented on internal/status/status.go
> +func (r *Result) GetStatusIcon() string {
also shouldn't be exported

2021-04-08 15:09 UTC, sideninja commented on pkg/flowcli/services/status.go
> +type Status struct {
add project
```go	
gateway gateway.Gateway
project *project.Project
logger  output.Logger
	```

2021-04-08 15:09 UTC, sideninja requested changes
Left you some more comments

2021-04-08 16:15 UTC, MaxStalker commented
I rebased this branch on `feature/shared-lib-ping`.
We really shall merge that one first :)

2021-04-08 16:35 UTC, sideninja commented on pkg/flowcli/services/status.go
> +type PingResponse struct {
This should go to the command as it was before. Just return:
```go
err := s.gateway.Ping()
network := s.project.NetworkByName(network)

return network, err
```

2021-04-08 16:37 UTC, sideninja requested changes
result should be part of ping command as suggested and after the fix it's ok

2021-04-08 16:54 UTC, MaxStalker commented
Let's bring these changes to Status service. And keep this PR solely about TabWriter :)

2021-04-09 15:15 UTC, sideninja approved these changes
Looks good

2021-04-09 15:16 UTC, merged