Nialexsan/update scaffolds
onflow/flow-cli pull request #1827
Opened 2024-11-14 15:42 UTC by nialexsan

Closes #1795

## Description

updated scaffolds/starters

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2024-11-20 21:05 UTC, nvdtf approved these changes

2024-11-20 23:44 UTC, chasefleming commented
Who is asking for this? We've removed a lot of scaffolds because they quickly get out of date and are hard to maintain. The goal was to move more towards reducing the scaffolds entirely. This puts us in the other direction.

2024-11-21 00:07 UTC, nialexsan commented on scaffolds.json
> -    "repo": "https://github.com/nvdtf/flow-nft-scaffold.git",
this project was not published, but now it is
it seems Navid took it down and restored later

2024-11-21 00:08 UTC, nialexsan commented on scaffolds.json
> +    "repo": "https://github.com/nialexsan/fcl-nextjs-quickstart.git",
this project was mentioned in the flow overview document:
https://developers.flow.com/ecosystem/overview

2024-11-21 00:10 UTC, nialexsan commented
the initial take on this was to replace scaffolds with starters, which seems to be the same thing with a different name

2024-11-21 20:23 UTC, chasefleming requested changes
Re other discussions offline, I think we should close this PR

2025-03-31 22:34 UTC, chasefleming commented
Closing since we will deprecate scaffolds

2025-03-31 22:34 UTC, closed without merging