Update Guidelines
onflow/flow-cli pull request #250
Opened 2021-05-12 15:41 UTC by sideninja

Update guidelines with the new rule about the amount of output.

Related issue: #249

2021-05-13 17:00 UTC, psiemens requested changes

2021-05-13 17:00 UTC, psiemens commented on CONTRIBUTING.md
> +Result output should include only information that is commonly used and releavant,
```suggestion
Result output should include only information that is commonly used and relevant, 
```

2021-05-13 17:59 UTC, psiemens approved these changes

2021-05-14 22:47 UTC, Kay-Zee approved these changes

2021-05-17 11:44 UTC, merged