make loader accept the latest valid flow json in path
onflow/flow-cli pull request #348
Opened 2021-08-02 19:55 UTC by bjartek

Closes #335 

## Description

Rewrites the loader logic so that it will always accept the latest valid flow.json in the path sent in. So first global flow.json then local flow.json

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2021-08-02 20:34 UTC, bjartek commented
Not sure what doc to change here really.

2021-08-03 11:39 UTC, sideninja requested changes
The config composition shouldn't be removed but amended. The problem with the current change is that if you want to use composition to load configurations it only takes the last configuration, whereas the intended functionality is to load configs and merge all values but overwrite properties if they have the same key, later sources' properties overwrite earlier ones (https://docs.onflow.org/flow-cli/security/#composing-multiple-configuration-files), similar to how Object.assign works in JS. 

The change to the functionality should be that if there is a local config present load only that config, if that config is not found then load global, but if configs are specified by using `-f` flag then we should keep the composition. 

You could check here (https://github.com/onflow/flow-cli/blob/f43841f1a0306e4ebfb5b00ccf3eeff6f13846c1/pkg/flowkit/config/loader.go#L109) if the paths are equal to default (local and global flow.json) and if local flow.json is found then ignore loading global (you can break the for loop if found local and if the only other provided path is global flow.json)

2021-08-03 17:34 UTC, bjartek commented
It is better now? I revertetd all the tests and added some more logic. Not sure how to test with afero and homedir though

2021-08-03 19:08 UTC, bjartek commented
So right now if -f is not used that is the configPaths are the default ones we load first the last config (default) then the first (global) and error if neither is found. If configPaths are anything else we load everything and merge, but then all files must be present. 

The previous logic actually enabled you to specify -f flow.json -f /some/other/flow.json and if flow.json was not present it would allow it, and I find that to be illogical.

2021-08-04 09:43 UTC, sideninja commented
> So right now if -f is not used that is the configPaths are the default ones we load first the last config (default) then the first (global) and error if neither is found. If configPaths are anything else we load everything and merge, but then all files must be present.
> 
> The previous logic actually enabled you to specify -f flow.json -f /some/other/flow.json and if flow.json was not present it would allow it, and I find that to be illogical.

Yes that is true and a good fix for it, however, now that I think about this I think that it would be best if the config command would not allow specifying additional configs by using `-f` flag since it's not intuitive to which file the command saves.

2021-08-04 11:37 UTC, bjartek commented
So we should just error out if the config is not default in the config cmd layer?

2021-08-04 12:31 UTC, sideninja commented
> Or if you have a single entry to -f it could work?

Right, yeah, single entry would be OK.

2021-08-04 14:14 UTC, bjartek commented
But this is best handled in the command layer riht? Because the current logic is valid elsewhere?

2021-08-04 14:30 UTC, sideninja commented
> But this is best handled in the command layer right? Because the current logic is valid elsewhere?

Exactly.

2021-08-05 07:47 UTC, sideninja commented on pkg/flowkit/config/loader_test.go
> +func Test_AllowMissingocalJson(t *testing.T) {
```suggestion
func Test_AllowMissingLocalJson(t *testing.T) {
```

2021-08-05 07:50 UTC, sideninja approved these changes
Left a small comment, otherwise, another great contribution, thank you 🙌

2021-08-24 07:43 UTC, merged