Added CLI Feature: Hot commands
onflow/flow-cli pull request #406
Opened 2021-10-30 11:59 UTC by sakshamb2113

Fixes #14

## Description

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2021-11-02 08:46 UTC, sideninja commented on internal/quick/deploy.go
> +		Short:   "Deploy contracts",
Deploy all project contracts

2021-11-02 08:54 UTC, sideninja commented on internal/quick/run.go
> +		project.DeployCommand.Cmd.Run(cmd, args)
Wouldn't this two commands be swapped in order?

2021-11-02 08:57 UTC, sideninja requested changes
Great effort so far, one thing that is problematic and needs changing is the fact that if you now use help with any of the commands you get a "hot commands" section, so for example, if I try to run `flow accounts --help` I will get first an empty "hot commands" section, but the way we want this to work is to only show that on the top "flow" command help.

2021-11-06 20:06 UTC, sakshamb2113 commented
I have made the changes and updated the code. Could you please have a look at it now ?

2021-11-10 18:13 UTC, sideninja approved these changes
Great improvement, LGTM

2021-11-26 14:07 UTC, merged