Feature/Enable host configuration for dev wallet
onflow/flow-cli pull request #517
Opened 2022-06-09 16:59 UTC by sukantoraymond

Closes #515 515

## Description

This PR enable cli users to add custom configuration for dev-wallet host by adding the flag --wallet-host in dev-wallet command. Example of this command is flow dev-wallet --wallet-host "http://localhost:8081" (default value is http://localhost:8080)
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

2022-06-10 08:05 UTC, sideninja commented on internal/tools/wallet.go
> +	Host string `default:"http://localhost:8080" flag:"wallet-host" info:"Host for access node connection"`
```suggestion
	Host string `default:"http://localhost:8080" flag:"emulator-host" info:"Host for access node connection"`
```

2022-06-10 08:10 UTC, sideninja requested changes
There are no doc updates.

2022-06-10 14:59 UTC, sukantoraymond commented on internal/tools/wallet.go
> +	Host string `default:"http://localhost:8080" flag:"wallet-host" info:"Host for access node connection"`
addressed

2022-06-14 23:33 UTC, psiemens commented on internal/tools/wallet.go
> +	Host string `default:"http://localhost:8080" flag:"emulator-host" info:"Host for access node connection"`
```suggestion
	Host string `default:"http://localhost:8888" flag:"emulator-host" info:"Host for access node connection"`
```

It looks like the emulator bundled with the CLI no longer exposes a server on port 8080. Should this be `http://localhost:8888` now?

2022-06-15 20:41 UTC, sukantoraymond commented on docs/tools.md
> -- Valid inputs: Number
deleted this because its not on the flags list in codebase

2022-06-20 13:27 UTC, sideninja approved these changes
Thank you, LGTM

2022-06-21 14:44 UTC, merged