Keys generate & derive cleanup, bip44 support for generate
onflow/flow-cli pull request #644
Opened 2022-08-30 09:50 UTC by bluesign

Closes #600

## Description

Will add documentation if this PR looks good. 

For contributor use:

- [ ] Targeted PR against `master` branch
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [X] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [X] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2022-08-30 09:52 UTC, bluesign commented
Can be reviewed easier when https://github.com/onflow/flow-cli/pull/628 merged. Was not sure how to make the PR tbh.

2022-08-31 08:39 UTC, sideninja commented on internal/keys/generate.go
> +	if generateFlags.Seed != "" {
Add a warning to prefer using mnemonic for key generation.

2022-08-31 08:49 UTC, sideninja commented on pkg/flowkit/keys.go
> +
```suggestion
```

2022-08-31 08:52 UTC, sideninja commented on pkg/flowkit/services/keys.go
> +
```suggestion
```

2022-08-31 08:53 UTC, sideninja requested changes
The tests for the new mnemonic keys are needed. Will pass another review after.

2022-08-31 08:53 UTC, sideninja commented on pkg/flowkit/services/keys.go
> +
```suggestion
```

2022-08-31 09:28 UTC, bluesign commented
@sideninja for the test: expected result key for the path from mnemonic kind of test ?

2022-08-31 09:55 UTC, sideninja commented
> @sideninja for the test: expected result key for the path from mnemonic kind of test ?

To test if the derivation works from the provided memonic.

2022-08-31 10:45 UTC, bluesign commented
Added 2 tests, one for generic (lilac etc), one for ledger devices.

2022-09-05 10:07 UTC, sideninja approved these changes

2022-09-05 10:07 UTC, merged