P256 key generation with SLIP10
onflow/flow-cli pull request #688
Opened 2022-11-06 11:58 UTC by bluesign

Closes #???

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2022-11-07 19:57 UTC, sideninja commented
@bluesign can you please add a description of why this PR is an improvement?

2022-11-15 14:55 UTC, sideninja approved these changes

2022-11-15 15:59 UTC, tarakby requested changes
The P-256 curve key-derivation process is indeed described by SLIP10 and not BIP32. The multi-account FLIP also [mentions that](https://github.com/onflow/flips/blob/main/flips/20201125-bip-44-multi-account.md#path-levels).

The PR implementation is based on the package `github.com/lmars/go-slip10`. I had a look at its code base and I noticed that its tests only cover secp256k1 curve (unless I read wrong). As far as I can see, there are no tests for P-256 curve. 
One particular [function](https://github.com/lmars/go-slip10/blob/master/utils.go#L148) caught my attention and it doesn't seem correct in the P-256 case (it assumes `a=0` while that is only true for secp256k1). That would result in incorrect results, and that's why I'm not confident about using the package. 

SLIP10 [provides](https://github.com/satoshilabs/slips/blob/master/slip-0010.md#test-vectors) plenty of test vectors that we should be using to validate our implementation. I suggest we integrate those to our tests. If P-256 tests do not pass, we could restrict the CLI support to secp256k1 only for now, and work on a solution for P-256.

2022-11-15 15:59 UTC, tarakby commented on pkg/flowkit/services/keys_test.go
> +		assert.Equal(t, key.String(), "0x638dc9ad0eee91d09249f0fd7c5323a11600e20d5b9105b66b782a96236e74cf")
I'm wondering how the expected value was computed? Is there a "source of truth" tool that can be referenced?

2022-11-15 21:16 UTC, bluesign commented
@tarakby thanks for looking into. I actually tested with slip10 test vectors, but eventually I forgot to add tests here, I will add now.

2022-11-17 01:36 UTC, tarakby commented
Thank you @bluesign for updating the tests! 
Sorry if I wasn't clear. What I meant is to add tests for the current repo implementation, specifically for `newBip44AccountKey(..).PrivateKey()` function. I think using `github.com/lmars/go-slip10` is an internal implementation detail and that our tests should pass regardless of the internal method we use. If we were to use another package in the future, our implementation-agnostic test files would still be relevant. 
Since our implementation only works with the lower level of the derivation path (we do not output the intermediate keys), we could test our implementation only against the lower key in the test vector. I think there are 4 keys in total to test against in the test vector (2 for each curve). 
What do you think?

I can add a quick PR against yours if I'm bad at explaining with words 😄

2022-11-17 08:29 UTC, bluesign commented
@tarakby, that would be great; ( probably I am the one bad with understanding, I am not good at testing in general )

2022-11-17 09:44 UTC, sideninja commented
Just a note here but I feel this should be at some later time moved to Go SDK.

2022-11-19 11:51 UTC, bluesign commented
@tarakby that looks great, now I understand what you meant, I will merge them asap.

2022-11-21 17:58 UTC, bluesign commented
merged @tarakby changes and rebased.

2022-11-22 14:25 UTC, sideninja commented
@tarakby are we good now with this PR?

2022-11-23 09:37 UTC, sideninja commented
I believe @tarakby is OOO so we will have to wait for his approval.

2022-12-01 23:12 UTC, tarakby approved these changes
Very Sorry for blocking this PR for so long! I missed approving it early and had limited online access

2022-12-01 23:13 UTC, tarakby commented
@bluesign @sideninja please feel free to merge at your convenience

2022-12-06 13:47 UTC, sideninja commented
> Very Sorry for blocking this PR for so long! I missed approving it early and had limited online access

No worries, I hope you had a nice time recharging.

2022-12-06 13:47 UTC, merged